title: I-Process
email: luke@lsiemens.com
description: > # this means to ignore newlines until "baseurl:"
  TODO--Description here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lsiemens.com" # the base hostname & protocol for your site
github_username: lsiemens

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
