# dependencies
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

permalink: pretty
paginate: 6
paginate_path: "/archive/page:num"

# setup
title: I-Process
url: "http://lsiemens.com"
baseurl: ""
email: luke@lsiemens.com
github_username: lsiemens

defaults:

  -

    scope:
      path: ""
      type: "posts"
    values:
       author: Luke Siemens
